### ISSUE TITLE
Error registering plugin x_printer

### ISSUE THREAD

**Issue by dtp24** [anhnt224/x_printer#2]
I encountered an issue where, if the BLUETOOTH_CONNECT permission is denied, the app doesn't work properly event after granting the permission. It only works after granting permission then restart the app.

`
E/GeneratedPluginRegistrant(18444): Error registering plugin x_printer, com.anhnt.x_printer.XPrinterPlugin
E/GeneratedPluginRegistrant(18444): java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@37483419: AdapterService getBondedDevices
E/GeneratedPluginRegistrant(18444): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2456)
E/GeneratedPluginRegistrant(18444): 	at android.os.Parcel.createException(Parcel.java:2440)
E/GeneratedPluginRegistrant(18444): 	at android.os.Parcel.readException(Parcel.java:2423)
E/GeneratedPluginRegistrant(18444): 	at android.os.Parcel.readException(Parcel.java:2365)
E/GeneratedPluginRegistrant(18444): 	at android.bluetooth.IBluetooth$Stub$Proxy.getBondedDevices(IBluetooth.java:3358)
E/GeneratedPluginRegistrant(18444): 	at android.bluetooth.BluetoothAdapter.getBondedDevices(BluetoothAdapter.java:2498)
E/GeneratedPluginRegistrant(18444): 	at com.anhnt.x_printer.BleManager.<init>(BleManager.kt:62)
E/GeneratedPluginRegistrant(18444): 	at com.anhnt.x_printer.XPrinterPlugin.onAttachedToEngine(XPrinterPlugin.kt:70)
E/GeneratedPluginRegistrant(18444): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:147)
E/GeneratedPluginRegistrant(18444): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:134)
E/GeneratedPluginRegistrant(18444): 	at java.lang.reflect.Method.invoke(Native Method)
E/GeneratedPluginRegistrant(18444): 	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
E/GeneratedPluginRegistrant(18444): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:388)
E/GeneratedPluginRegistrant(18444): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:289)
E/GeneratedPluginRegistrant(18444): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:270)
E/GeneratedPluginRegistrant(18444): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:250)
E/GeneratedPluginRegistrant(18444): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:170)
E/GeneratedPluginRegistrant(18444): 	at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundExecutor.lambda$startBackgroundIsolate$0$io-flutter-plugins-firebase-messaging-FlutterFirebaseMessagingBackgroundExecutor(FlutterFirebaseMessagingBackgroundExecutor.java:169)
E/GeneratedPluginRegistrant(18444): 	at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundExecutor$$ExternalSyntheticLambda0.run(Unknown Source:8)
E/GeneratedPluginRegistrant(18444): 	at android.os.Handler.handleCallback(Handler.java:938)
E/GeneratedPluginRegistrant(18444): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/GeneratedPluginRegistrant(18444): 	at android.os.Looper.loopOnce(Looper.java:201)
E/GeneratedPluginRegistrant(18444): 	at android.os.Looper.loop(Looper.java:288)
E/GeneratedPluginRegistrant(18444): 	at android.app.ActivityThread.main(ActivityThread.java:7881)
E/GeneratedPluginRegistrant(18444): 	at java.lang.reflect.Method.invoke(Native Method)
E/GeneratedPluginRegistrant(18444): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
E/GeneratedPluginRegistrant(18444): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
`

**Comment by anhnt224** [comment]
This issue has been fixed in version 0.0.7
